jobqueue:
  lsf:
    # Cluster slots are reserved in chunks.
    # This specifies the chunk size.
    ncpus: 48

    # How many dask worker processed to run per chunk.
    # (Leave one thread empty for garbage collection.)
    processes: 40

    # How many threads to use in each chunk.
    # (Use just one thread per process -- no internal thread pools.)
    cores: 40

    memory: 720GB   # 15 GB per slot
    walltime: 01:00 # Set to 1:00 for access to the short queue
    mem: 720000000000
    use-stdin: true
    log-directory: job-logs
    name: multiresolution-mesh-creator

    # Extra arguments to bsub can be provided here.
    # For example, this charges the job to cosem's budget, rather than your default account.
    project: cellmap

distributed:
  scheduler:
    work-stealing: true

  worker:
    memory:
      target: 0.0
      spill: 0.0
      pause: 0.0
      terminate: 0.0

  admin:
    log-format: '[%(asctime)s] %(levelname)s %(message)s'
    tick:
      interval: 20ms  # time between event loop health checks
      limit: 3h       # time allowed before triggering a warning
