required_settings:
        input_path: ../test_meshes           # Path to lod 0 meshes:
        output_path: ../test_meshes_output   # Path to write out multires meshes:
        num_lods: 6                         # Number of levels of detail:
        box_size: 256                       # lod 0 box size:


optional_decimation_settings:
        skip_decimation: False         # Skip mesh decimation if meshes exist; default is false
        decimation_factor: 2           # Factor by which to decimate faces at each lod, ie factor**lod; default is 2
        aggressivness: 7               # Aggressiveness to be used for decimation; default is 7
