required_settings:
        # Path to lod 0 meshes:
        input_path: /groups/scicompsoft/home/ackermand/Programming/multiresolution-mesh-creator/test_meshes
        # Path to write out multires meshes:
        output_path: /groups/scicompsoft/home/ackermand/Programming/multiresolution-mesh-creator/test_meshes_output
        # Number of levels of detail:
        num_lods: 6
        # lod 0 box size:
        box_size: 4

optional_decimation_settings:
        # Skip mesh decimation if meshes exist; default is false
        skip_decimation: False
        # Factor by which to decimate faces at each lod, ie factor**lod; default is 2
        decimation_factor: 2
        # Aggressiveness to be used for decimation; default is 7
        aggressivness: 7
