required_params:
        # Path to lod 0 meshes:
        input_path: /groups/cosem/cosem/ackermand/meshesForWebsite/res1decimation0p05/jrc_hela-1/er_seg
        # Path to write out multires meshes:
        output_path: /groups/cosem/cosem/ackermand/meshesForWebsite/res1decimation0p05/jrc_hela-1/test_simpler_multires/temp
        # Number of levels of detail:
        num_lods: 6
        # lod 0 box size:
        box_size: 256

optional_decimation_params:
        # Skip mesh decimation if meshes exist; default is false
        skip_decimation: False
        # Factor by which to decimate faces at each lod, ie factor**lod; default is 2
        decimation_factor: 2
        # Aggressiveness to be used for decimation; default is 7
        aggressivness: 7
